Kanban/Models/AtividadeModel.cs
using System.ComponentModel.DataAnnotations;

namespace Kanban.Models
{
    public class AtividadeModel
    {
       
        public int Id { get; set; }
        public int Matricula { get; set; }
        public string? Titulo { get; set; }
        public string? Descricao { get; set; }
        public DateTime DataCriacao { get; set; } = DateTime.Now;
        public int StatusId { get; set; }
        public StatusModel Status { get; set; }
    }
}

Kanban/Models/StatusModel.cs
namespace Kanban.Models
{
    public class StatusModel
    {
        public int Id { get; set; }

        public string? Nome { get; set; }
    }
}

Kanban/Controllers/AtividadeController.cs
using Kanban.Dto;
using Kanban.Services.Atividade;
using Microsoft.AspNetCore.Mvc;

namespace Kanban.Controllers
{
    public class AtividadeController : Controller
    {
        private readonly IAtividadeInterface _atividadeInterface;
        public AtividadeController(IAtividadeInterface atividadeInterface)
        {
            _atividadeInterface = atividadeInterface;
        }

        public async Task<IActionResult> Index()
        {
            var atividades = await _atividadeInterface.BuscarAtividade();

            return View(atividades);
        }

        public async Task<IActionResult> Cadastrar()
        {
            var status = await _atividadeInterface.BuscarStatus();
            ViewBag.Status = status;
           
            return View();
        }
        public async Task<IActionResult> Excluir(int id)
        {
            var atividade = await _atividadeInterface.ExcluirAtividade(id);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> MudarCard(int id)
        {
            var atividade = await _atividadeInterface.MudarCard(id);
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> CardAnterior(int id)
        {
            var atividade = await _atividadeInterface.CardAnterior(id);
            return RedirectToAction("Index");
        }


        [HttpPost]
        public async Task<IActionResult> Cadastrar(CadastroAtividadeDto cadastroAtividadeDto)
        {
            if (ModelState.IsValid)
            {
                var cadastro = await _atividadeInterface.CadastrarAtividade(cadastroAtividadeDto);
                return RedirectToAction("Index");
            }
            else
            {
                var status = await _atividadeInterface.BuscarStatus();
                ViewBag.Status = status;
                return View(cadastroAtividadeDto);
            }
          
        }

    }
}

Kanban/Controllers/HomeController.cs
using System.Diagnostics;
using Kanban.Services.Atividade;
using Microsoft.AspNetCore.Mvc;

namespace Kanban.Controllers;

    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }


    }   

Kanban/Views/Atividade/Cadastrar.cshtml
@using Kanban.Dto
@model CadastroAtividadeDto

<div class="container">

    <form method="post" asp-controller="Atividade" asp-action="Cadastrar">

        <div>
            <label class="col-form-label-lg">Titulo</label>
            <input type="text" class="form-control" asp-for="Titulo" /> 
            <span class="text-danger" asp-validation-for="Titulo"></span>
        </div>

        <div>
            <label class="col-form-label-lg">Descrição</label>
            <input type="text" class="form-control" asp-for="Descricao" />
            <span class="text-danger" asp-validation-for="Descricao"></span>
        </div>

        <div>
            <label class="col-form-label-lg">Status</label>
            <select class="form-select"
                asp-for="StatusId"
                asp-items= "@(new SelectList(ViewBag.Status,"Id","Nome"))">

            </select>
        </div>

        <div class="d-flex mt-3">
            <button type="submit" class="btn btn-primary w-50 ">Cadastrar</button>
            <a class="btn btn-danger w-50" asp-action="Index" asp-controller="Atividade">Voltar</a>
        </div>
    </form>

</div>

Kanban/Views/Atividade/Index.cshtml
@using Kanban.Models
@model List<AtividadeModel>

<div class="container">
    <div class="row">
        <div class="col-4">
         
            <h2>Pendentes</h2>

            @if (Model.Count > 0)
            {
                foreach (var atividade in Model.Where(x => x.Status.Nome == "Pendente"))
                {
                    <div class="card text-center">
                        <div class="card-header">
                            @atividade.Status.Nome
                        </div>
                        <div class="card-body">
                          <h5> @atividade.Titulo </h5>
                            <p> @atividade.Descricao </p>
                            <a asp-action="MudarCard" asp-controller="Atividade" asp-route-id="@atividade.Id" class="btn btn-success">Proximo Card</a>
                        </div>
                        <div class="card-footer">
                            @atividade.DataCriacao.ToString("dd/MM/yyyy HH:mm")
                        </div>
                    </div>
                }
            }

        </div>
        <div class="col-4">
            
            <h2>Em Andamento</h2>

            @if (Model.Count > 0)
            {
                foreach (var atividade in Model.Where(x => x.Status.Nome == "Em Andamento"))
                {
                    <div class="card text-center">
                        <div class="card-header">
                            @atividade.Status.Nome
                        </div>
                        <div class="card-body">
                            <h5> @atividade.Titulo </h5>
                            <p> @atividade.Descricao </p>
                            <a asp-action="CardAnterior" asp-controller="Atividade" asp-route-id="@atividade.Id" class="btn btn-primary">Card Anterior</a>
                            <a asp-action="MudarCard" asp-controller="Atividade" asp-route-id="@atividade.Id" class="btn btn-success">Proximo Card</a>
                        </div>
                        <div class="card-footer">
                            @atividade.DataCriacao.ToString("dd/MM/yyyy HH:mm")
                        </div>
                    </div>
                }
            }
        </div>
        <div class="col-4">
          
            <h2>Finalizada</h2>

            @if (Model.Count > 0)
            {
                foreach (var atividade in Model.Where(x => x.Status.Nome == "Finalizada"))
                {
                    <div class="card text-center">
                        <div class="card-header">
                            @atividade.Status.Nome
                        </div>
                        <div class="card-body">
                            <h5> @atividade.Titulo </h5>
                            <p> @atividade.Descricao </p>
                            <a asp-action="CardAnterior" asp-controller="Atividade" asp-route-id="@atividade.Id" class="btn btn-primary">Card Anterior</a>
                            <a asp-action="Excluir" asp-controller="Atividade" asp-route-id="@atividade.Id" class="btn btn-danger">Deletar Card</a>
                        </div>
                        <div class="card-footer">
                            @atividade.DataCriacao.ToString("dd/MM/yyyy HH:mm")
                        </div>
                    </div>
                }
            }
        </div>
    </div>
</div>

Kanban/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Kanban/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Kanban</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/lumen.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Kanban.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Atividade" asp-action="Index">Kanban</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                        </li>
                        <a class="nav-link text-dark" asp-area="" asp-controller="Atividade" asp-action="Cadastrar">Cadastrar</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Kanban - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>